### ISSUE TITLE
Start import/export

### ISSUE THREAD

**Issue by hipstersmoothie** [Dschungelabenteuer/vite-plugin-entry-shaking#11]
The readme says the following aren't supported

```
import * as xxx from '…'
export * from '…'
```

I've also found this isn't supported

```
export * as xxx from '…'
```

Do you think it would be possible to modify the code to handle these? Or would it be too much work?

**Comment by Dschungelabenteuer** [comment]
Thank you for your question, especially because it got me to think further about these limitations. Could you provide an example of issue you're running into when using the `export * as Something from '…'` syntax? The current phrasing of limitations may be misleading because it does not states wether it applies to entry points (files exporting all code) or to consuming code (files importing code from entry points), and I think it might be outdated now.

**Comment by Dschungelabenteuer** [comment]
Closing stale issue
