### ISSUE TITLE
[Bug]: parse error when export * from "xxx.tsx"

### ISSUE THREAD

**Issue by Shunjun** [Dschungelabenteuer/vite-plugin-entry-shaking#49]
### What does the bug relate to?

- [X] Plugin's core
- [ ] Debugger

### Describe the bug

I have lots of barrel file like
```
export * from "a.tsx"
export * from "b.tsx"
```
but es-module-lexer can not parse the tsx file.
Is it possible to use another parser to parse tsx file

### To Reproduce

Could not analyze entry file "path/to/a.tsx"

### Vite version

5.2.7

**Comment by Dschungelabenteuer** [comment]
This is undeed a known limitation of `es-module-lexer` 

### About switching `es-module-lexer`

Using another parser would likely require a full rewrite because this plugin mostly relies on its API. I'm afraid I'm not willing to re-considerate that choice for these reasons, at least for now. It was written on top of `es-module-lexer` because it is tiny and probably one of the most efficient way of ensuring this plugin's logic: 
- we only need to know about import/export statements (and that's precisely what it does), 
- we need it to be fast (under the hood it runs C through wasm)

### However

That doesn't mean we have to completely ignore JSX, though! I completely understand the legitimate needs, and you're not the first one to mention JSX (see #13). Back then, I considered adding a "loader" option but never went further.

Right now, I'm rather considering just making it work without any further configuration by using `esbuild` as an optional peer dependency (since it's already used by Vite to support JSX out of the box).

I think this should be fairly easy to implement. However, I'm a bit busy and won't have enough time to test it thoroughly, I can still try and deploy a new minor release with JSX support flagged as an experimental feature, WDYT?
